version = 1

test_patterns = [
    "server/**/*_test.go",
    "template/tests/**/*.test.js"
]

exclude_patterns = [
    "server/database/migrations/**",
    "server/public/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/malusev998/malusev998/server"]
  import_root = "github.com/malusev998/malusev998/"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  style_guide = "airbnb"
  dialect = "typescript"
