# https://taskfile.dev

version: '3'

vars:
  EXE: dusanmalusev{{exeExt}}
  CLIENT_DIST: dist/
  CLIENT_SSR_SERVER_DIR: dist/dusanmalusev-frontend/server
  CLIENT_SSR_BROWSER_DIR: dist/dusanmalusev-frontend/browser
  VERSION:
    sh: |
      TAG=$(git tag -l | head -n 1)
      if [ -z "$TAG" ]; then TAG=$(git log -n 1 --format=%h); fi;
      echo $TAG
tasks:
  default:
    cmds:
      - task: client-docker
      - task: server-docker
    silent: true
  clean:
    cmds:
      - rm -rf client/dist
      - rm -f server/{{.EXE}}
    client: true
  client-build:
    dir: client
    cmds:
      - npm run build:ssr
      - mkdir -p {{.CLIENT_SSR_SERVER_DIR}}/app
      - cp -r {{.CLIENT_SSR_BROWSER_DIR}}/ {{.CLIENT_SSR_SERVER_DIR}}/app
  client-dev:
    dir: client
    cmds:
      - npm run dev:ssr
  client-serve:
    dir: 'client/{{.CLIENT_SSR_SERVER_DIR}}'
    deps: [client-build]
    cmds:
      - node main.js
  client-docker:
    dir: client
    deps: [client-build]
    cmds:
      - docker build --build-arg PORT=4000 --build-arg DIST=dist/dusanmalusev-frontend/server -t dusanmalusev-front:{{.VERSION}} .
  server-build:
    dir: server
    cmds:
      - go clean
      - go build -p 4 -race -o {{.EXE}}
  server-docker:
    dir: server
    deps: [server-build]
    cmds:
      - docker build --build-arg BINARY_NAME={{.EXE}} --build-arg PORT=3000 -t dusanmalusev-server:{{.VERSION}} .
  server-dev:
    dir: server
    cmds:
      - go run main.go
  server-serve:
    dir: server
    deps: [server-build]
    cmds:
      - ./{{.EXE}}
