debug: true # Debug enables PProf
locale: en

postgres:
  host: localhost
  user: postgres
  password: postgres
  dbname: dusanmalusev
  port: 5432
  timezone: UTC
  sslmode: false
  logfile: ./log/db.log
  max_connection_lifetime: 1h
  max_connection_idle_time: 24h
  health_check: 15m
  max_conns: 20
  min_conns: 5
  lazy: true

subscription:
  send_email_on_subscription: true
  send_email_on_unsubscription: true

# supported logging - debug, info, warning, error
logging:
  level: info # Logger instance used in API
  console: true # Console logging
  file: ./log/server.log

http:
  prefork: false
  address: :4000 # HTTP Address
