version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dusanmalusev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - dusanmalusev
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - dusanmalusev
    environment:
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
        - "5000:80"
    depends_on:
        - postgres
  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    networks:
      - dusanmalusev
  redislabs:
    image: redislabs/redisinsight:1.8.3
    ports:
      -  8001:8001
    depends_on:
      - redis
    volumes:
      - redis:/db
    networks:
      - dusanmalusev
networks:
  dusanmalusev:
    driver: bridge
volumes:
  postgres:
  redis:
