name: Linter
on:
  push:
    paths:
      - 'server/**'
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  Golint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: '--tests=false'
