name: 'GO Tidy'

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/gotidy.yml'
      - 'server/go.mod'
      - 'server/go.sum'
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Tidy
        working-directory: server
        run: make tidy
      - name: Set up Git
        working-directory: server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: dusanmalusev
        run: make git-setup
      - name: Commit and push changes
        working-directory: server
        run: make commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: Fix Go Modules
