name: 'Template build'

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'template/**'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - uses: actions/cache@v2
        with:
          path: template/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('template/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up Git
        run: make git-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make
        env:
          ENVIRONMENT: production
        working-directory: template
      - name: Commit and push changes
        run: make commit
        env:
          MESSAGE: UI Build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
